# Generated by Django 4.1.5 on 2023-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VI_app', '0002_alter_perevaladded_autumn_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.BooleanField(default=True),
        ),
    ]
