# Generated by Django 4.1.5 on 2023-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VI_app', '0004_alter_perevaladded_autumn_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='coord_id',
            new_name='coord',
        ),
    ]
